export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const PRODUCTS_SUCCESS ='PRODUCTS_SUCCESS'
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL'

/*** */

export const PRODUCT_REQUEST = 'PRODUCT_REQUEST'
export const PRODUCT_SUCCESS ='PRODUCT_SUCCESS'
export const PRODUCT_FAIL = 'PRODUCT_FAIL'
